[package]
name = "signal"
version = "0.1.0"
license = "MIT"
authors = ["Paul Colomiets <paul@colomiets.name>"]

[dependencies]
nix = "*"
libc = "*"

[dev-dependencies]
nix = { git = "git://github.com/carllerche/nix-rust" }
